<?php

namespace App\Libraries;

use CodeIgniter\HTTP\Files\UploadedFile;

/**
 * Validated, tenant-isolated storage for uploaded files.
 *
 * The previous code moved uploads straight into the web root
 * (`$file->move('uploads/assignments/', $file->getRandomName())`) with no
 * validation of extension, MIME type or size. Because that directory is served
 * directly by the web server, an uploaded `.php` file was executable — remote
 * code execution from any of the four upload forms.
 *
 * Files now live under `writable/uploads/{organisation}/{category}/`, which is
 * outside the document root, and are streamed back by FileController only to
 * members of the owning organisation.
 */
class FileStore
{
    /**
     * Upload categories and the extensions each accepts.
     */
    public const CATEGORIES = [
        'assignments' => ['pdf', 'doc', 'docx', 'zip', 'txt', 'png', 'jpg', 'jpeg'],
        'submissions' => ['pdf', 'doc', 'docx', 'zip', 'txt', 'png', 'jpg', 'jpeg'],
        'notices'     => ['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg'],
        'classworks'  => ['pdf', 'doc', 'docx', 'zip', 'txt', 'png', 'jpg', 'jpeg'],
        'avatars'     => ['png', 'jpg', 'jpeg', 'webp'],
    ];

    /**
     * Extension => acceptable MIME types. The extension alone is not trusted:
     * the detected type has to agree with it.
     */
    private const MIME_MAP = [
        'pdf'  => ['application/pdf'],
        'doc'  => ['application/msword'],
        'docx' => ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'],
        'zip'  => ['application/zip', 'application/x-zip-compressed', 'multipart/x-zip'],
        'txt'  => ['text/plain'],
        'png'  => ['image/png'],
        'jpg'  => ['image/jpeg'],
        'jpeg' => ['image/jpeg'],
        'webp' => ['image/webp'],
    ];

    public const MAX_BYTES = 8 * 1024 * 1024; // 8 MB

    /**
     * Validate and store an upload.
     *
     * @return string the stored file name
     *
     * @throws \RuntimeException when the file is rejected
     */
    public function store(UploadedFile $file, string $category, int $adminId): string
    {
        if (! isset(self::CATEGORIES[$category])) {
            throw new \InvalidArgumentException("Unknown upload category: {$category}");
        }

        if (! $file->isValid()) {
            throw new \RuntimeException($file->getErrorString());
        }

        if ($file->hasMoved()) {
            throw new \RuntimeException('That file has already been processed.');
        }

        if ($file->getSize() > self::MAX_BYTES) {
            throw new \RuntimeException('Files must be 8 MB or smaller.');
        }

        $extension = strtolower($file->getClientExtension());

        if (! in_array($extension, self::CATEGORIES[$category], true)) {
            throw new \RuntimeException(
                'Allowed file types: ' . implode(', ', self::CATEGORIES[$category]) . '.'
            );
        }

        // getMimeType() inspects the file contents rather than trusting the
        // browser-supplied Content-Type header.
        $mime = $file->getMimeType();

        if (isset(self::MIME_MAP[$extension]) && ! in_array($mime, self::MIME_MAP[$extension], true)) {
            throw new \RuntimeException('That file\'s contents do not match its ".' . $extension . '" extension.');
        }

        $directory = $this->directory($category, $adminId);

        if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
            throw new \RuntimeException('The upload directory could not be created.');
        }

        // A random name means a caller can never choose the path on disk.
        $name = $file->getRandomName();
        $file->move($directory, $name);

        return $name;
    }

    /**
     * Absolute path of a stored file, or null if the name is unsafe or missing.
     */
    public function path(string $category, string $name, int $adminId): ?string
    {
        if (! isset(self::CATEGORIES[$category])) {
            return null;
        }

        // Stored names are always generated by getRandomName(); anything else
        // is a traversal attempt.
        if (preg_match('/^[A-Za-z0-9_]+\.[A-Za-z0-9]+$/', $name) !== 1) {
            return null;
        }

        $path = $this->directory($category, $adminId) . $name;

        return is_file($path) ? $path : null;
    }

    /**
     * Delete a stored file, ignoring one that is already gone.
     */
    public function delete(?string $name, string $category, int $adminId): void
    {
        if ($name === null || $name === '') {
            return;
        }

        $path = $this->path($category, $name, $adminId);

        if ($path !== null) {
            @unlink($path);
        }
    }

    private function directory(string $category, int $adminId): string
    {
        return WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . $adminId . DIRECTORY_SEPARATOR . $category . DIRECTORY_SEPARATOR;
    }
}
